In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("/content/drive/MyDrive/Machine Learning/lung_cancer.csv")
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
num_df =df.drop(['Name','Surname'],axis=1)
names = num_df.columns
d = scaler.fit_transform(num_df)
scaled_df = pd.DataFrame(d, columns=names)
scaled_df
scaled_df.to_csv("lung_cancer_2147258.csv")

Understanding Independent variables using iloc function

In [ ]:
df.iloc[:,:-1].columns

Index(['Name', 'Surname', 'Age', 'Smokes', 'AreaQ', 'Alkhol'], dtype='object')

Understanding the dependent variable using iloc function


In [ ]:
df.iloc[:,6:7].columns

Index(['Result'], dtype='object')

Identifying unique value inside "dx_type" column using unique function

In [ ]:
df['Name'].unique()

array(['John', 'Camela', 'Alex', 'Diego', 'Cristiano', 'Mihail', 'Kathy',
       'Nicole', 'Ray', 'Fredric', 'Yul', 'Joan', 'Jane', 'Anna',
       'Katharine ', 'Barbra', 'Maggie ', 'Glenda ', 'Jane ',
       'Maximilian ', 'Gregory ', 'Sidney ', 'Rex ', 'Lee ', 'Paul ',
       'Rod ', 'John ', 'Gene ', 'Marlon ', 'Jack ', 'Peter ', 'Richard ',
       'Dustin ', 'Henry ', 'Robert ', 'Ellen ', 'Faye ', 'Diane ',
       'Sally ', 'Sissy ', 'Jessica ', 'Gwyneth ', 'Halle ', 'Nicole ',
       'Charlize ', 'Barbra ', 'Ernest ', 'Alec ', 'Charlton '],
      dtype=object)

Identifying missing values using isnull function - 
  True: represents the missing value
  False: represents no missing value

In [ ]:
df.isnull()

Name  Surname    Age  Smokes  AreaQ  Alkhol  Result
0   False    False  False   False  False   False   False
1   False    False  False   False  False   False   False
2   False    False  False   False  False   False   False
3   False    False  False   False  False   False   False
4   False    False  False   False  False   False   False
5   False    False  False   False  False   False   False
6   False    False  False   False  False   False   False
7   False    False  False   False  False   False   False
8   False    False  False   False  False   False   False
9   False    False  False   False  False   False   False
10  False    False  False   False  False   False   False
11  False    False  False   False  False   False   False
12  False    False  False   False  False   False   False
13  False    False  False   False  False   False   False
14  False    False  False   False  False   False   False
15  False    False  False   False  False   False   False
16  False    False  False   False  False   False   False
17  False    False  False   False  False   False   False
18  False    False  False   False  False   False   False
19  False    False  False   False  False   False   False
20  False    False  False   False  False   False   False
21  False    False  False   False  False   False   False
22  False    False  False   False  False   False   False
23  False    False  False   False  False   False   False
24  False    False  False   False  False   False   False
25  False    False  False   False  False   False   False
26  False    False  False   False  False   False   False
27  False    False  False   False  False   False   False
28  False    False  False   False  False   False   False
29  False    False  False   False  False   False   False
30  False    False  False   False  False   False   False
31  False    False  False   False  False   False   False
32  False    False  False   False  False   False   False
33  False    False  False   False  False   False   False
34  False    False  False   False  False   False   False
35  False    False  False   False  False   False   False
36  False    False  False   False  False   False   False
37  False    False  False   False  False   False   False
38  False    False  False   False  False   False   False
39  False    False  False   False  False   False   False
40  False    False  False   False  False   False   False
41  False    False  False   False  False   False   False
42  False    False  False   False  False   False   False
43  False    False  False   False  False   False   False
44  False    False  False   False  False   False   False
45  False    False  False   False  False   False   False
46  False    False  False   False  False   False   False
47  False    False  False   False  False   False   False
48  False    False  False   False  False   False   False
49  False    False  False   False  False   False   False
50  False    False  False   False  False   False   False
51  False    False  False   False  False   False   False
52  False    False  False   False  False   False   False
53  False    False  False   False  False   False   False
54  False    False  False   False  False   False   False
55  False    False  False   False  False   False   False
56  False    False  False   False  False   False   False
57  False    False  False   False  False   False   False
58  False    False  False   False  False   False   False

In [ ]:
df.fillna(0)

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

Normalizing the dataset using min-max normalization technique. It is applied to columns with numeric value "age" in this case

In [ ]:

# copy the data
# df_min_max_scaled = df.copy()
# # apply normalization techniques by Column 1
# column = 'Age'
# df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())    
# # view normalized data
# display(df_min_max_scaled)


from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
num_df =df.drop(['Name','Surname'],axis=1)
names = num_df.columns
d = scaler.fit_transform(num_df)
scaled_df = pd.DataFrame(d, columns=names)
scaled_df
scaled_df.to_csv("lung_cancer_2147258.csv")

Age    Smokes     AreaQ  Alkhol  Result
0   0.288136  0.088235  0.444444   0.500     1.0
1   0.152542  0.588235  0.111111   0.625     1.0
2   0.203390  0.000000  0.444444   0.250     0.0
3   0.169492  0.000000  0.777778   0.125     0.0
4   0.847458  0.117647  0.444444   0.750     1.0
5   0.271186  0.000000  1.000000   0.000     0.0
6   0.677966  0.441176  1.000000   0.000     0.0
7   0.067797  0.352941  0.444444   0.250     0.0
8   0.457627  0.058824  0.555556   0.000     0.0
9   0.576271  0.529412  0.333333   0.625     1.0
10  0.254237  0.117647  0.777778   0.000     0.0
11  0.000000  0.294118  0.555556   0.375     0.0
12  0.118644  0.058824  0.444444   0.125     0.0
13  0.169492  0.588235  0.111111   1.000     1.0
14  0.271186  0.735294  0.333333   1.000     1.0
15  0.355932  0.529412  0.777778   0.125     0.0
16  0.406780  0.647059  0.222222   0.625     1.0
17  0.016949  0.352941  0.777778   0.000     0.0
18  0.745763  0.147059  0.333333   0.375     1.0
19  0.932203  0.294118  0.666667   0.750     1.0
20  0.627119  0.441176  0.000000   0.375     1.0
21  0.254237  0.235294  0.777778   0.125     0.0
22  0.067797  0.588235  0.555556   0.250     0.0
23  0.440678  0.147059  0.777778   0.125     0.0
24  1.000000  0.088235  0.111111   0.750     1.0
25  0.050847  0.588235  0.444444   0.375     0.0
26  0.322034  0.441176  0.555556   0.250     0.0
27  0.271186  0.352941  0.777778   0.000     0.0
28  0.627119  0.588235  0.000000   0.500     1.0
29  0.372881  0.588235  0.111111   0.875     1.0
30  0.305085  0.382353  0.444444   0.250     0.0
31  0.644068  0.588235  0.222222   0.375     1.0
32  0.491525  0.441176  0.000000   1.000     1.0
33  0.745763  0.735294  0.222222   0.500     1.0
34  0.135593  0.294118  0.666667   0.250     0.0
35  0.118644  0.588235  0.777778   0.250     0.0
36  0.694915  0.588235  0.222222   0.500     1.0
37  0.745763  0.441176  0.444444   0.625     1.0
38  0.254237  0.735294  0.777778   0.250     0.0
39  0.322034  0.294118  0.444444   0.375     0.0
40  0.542373  0.588235  0.111111   0.500     1.0
41  0.491525  0.352941  0.777778   0.000     0.0
42  0.864407  0.588235  0.444444   0.500     1.0
43  0.762712  0.588235  0.333333   0.625     1.0
44  0.355932  0.441176  0.666667   0.250     0.0
45  0.050847  0.588235  0.777778   0.375     0.0
46  0.220339  0.588235  0.888889   0.500     0.0
47  0.169492  0.294118  0.333333   0.125     0.0
48  0.593220  0.588235  0.555556   0.375     1.0
49  0.745763  0.588235  0.444444   0.750     1.0
50  0.406780  0.352941  0.555556   0.250     0.0
51  0.440678  0.882353  0.000000   0.750     1.0
52  0.135593  1.000000  0.000000   1.000     1.0
53  0.288136  0.588235  0.444444   0.125     0.0
54  0.135593  0.382353  0.555556   0.125     0.0
55  1.000000  0.588235  0.444444   0.500     1.0
56  0.966102  0.441176  0.222222   0.625     1.0
57  0.423729  0.882353  0.222222   1.000     1.0
58  0.559322  0.735294  0.888889   0.000     0.0

**Apply KNN for the preprocessed dataset use 5 different K Values and 3 different distance measures**

In [ ]:
x = num_df.iloc[:, :-1].values
y = num_df.iloc[:, -1].values


In [ ]:
x_train, x_test, y_train,  y_test = train_test_split(x, y, test_size=0.20)

In [ ]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=5,p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)
print(y_pred)

[1 0 0 0 1 0 0 1 0 1 0 1]


In [ ]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12

[[7 0]
 [0 5]]


In [ ]:
k = 2;
pn = 1;
for i in range(2,7):
  for n in range(1,4):
    classifier = KNeighborsClassifier(n_neighbors=2,p=1)
    classifier.fit(x_train, y_train)
    y_pred = classifier.predict(x_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test,y_pred))
    print("Accuracy score ")
    print(metrics.accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12

[[7 0]
 [0 5]]
Accuracy score 
1.0
-------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12

[[7 0]
 [0 5]]
Accuracy score 
1.0
-------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5

    accuracy                        

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=2,p=1)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print("Accuracy score ")
print(metrics.accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12

[[7 0]
 [0 5]]
Accuracy score 
1.0


NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB

# instantiate the model
gnb = GaussianNB()

# fit the model
gnb.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(x_test)

y_pred

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 1.0000
