In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn import tree
from sklearn.metrics import r2_score
from sklearn import model_selection
from sklearn import linear_model
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/lung_cancer.csv')

In [ ]:
df.describe()

Age     Smokes      AreaQ     Alkhol     Result
count  59.000000  59.000000  59.000000  59.000000  59.000000
mean   42.627119  15.067797   5.203390   3.237288   0.474576
std    16.235230   7.984607   2.461984   2.380517   0.503640
min    18.000000   0.000000   1.000000   0.000000   0.000000
25%    29.000000  10.000000   3.000000   1.000000   0.000000
50%    39.000000  15.000000   5.000000   3.000000   0.000000
75%    55.000000  20.000000   7.500000   5.000000   1.000000
max    77.000000  34.000000  10.000000   8.000000   1.000000

In [ ]:
df.head()


Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
df.shape

(59, 7)

In [ ]:
df.isnull().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [ ]:
def convertCatNum(dataset):
    le = LabelEncoder()
    dataset["Name"]=le.fit_transform(dataset["Name"])
    # le = LabelEncoder()
    # dataset["Surname"]=le.fit_transform(dataset["Surname"])
    return dataset

In [ ]:
df = convertCatNum(df.copy())

In [ ]:
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    27         Wick   35       3      5       4       1
1    27  Constantine   27      20      2       5       1
2     5     Anderson   30       0      5       2       0
3     1       Telles   28       0      8       1       0
4    10     Maradona   68       4      5       6       1

In [ ]:
df.drop('Name', axis=1,inplace=True)

In [ ]:
df.drop('Surname', axis=1,inplace=True)

In [ ]:
df.head()

Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [ ]:
def splitter(dataset):
    X=dataset.iloc[:,2:].values
    y=dataset.iloc[:,1].values
    SD=StandardScaler()
    X=SD.fit_transform(X)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=0)
    return X_train, X_test, y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = splitter(df.copy())

In [ ]:
def LogisticsRegression(dataset):
    LG=LogisticRegression(random_state=0)
    pred = LG.fit(X_train,y_train)
    pred = LG.predict(X_test)
    print("\nConfusion Matrix:\t")
    print(confusion_matrix(y_test, pred))
    print("\nAccuracy Score:\t")
    print(accuracy_score(y_test, pred))


In [ ]:
LogisticsRegression(df)


Confusion Matrix:	
[[0 0 0 0 0 1 0]
 [0 0 0 1 0 1 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 1 0 4 1]
 [0 0 0 0 0 0 0]]

Accuracy Score:	
0.3333333333333333
